In [1]:
from pymongo import MongoClient

In [2]:
mc = MongoClient("localhost", 27017, username='root', password='qiuqiu78')  # Mongo连接

In [3]:
db_vnpy = mc['stock_vnpy']  

In [4]:
db_vnpy['test'].insert({"goodsname":"apple","goodsdes":"hahaha","goodscount":2})

c:\vnstudio\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: insert is deprecated. Use insert_one or insert_many instead.
  """Entry point for launching an IPython kernel.


ObjectId('5f40db3de2beea4f7f8a889a')

In [5]:
 db_vnpy['test'].find()

In [6]:
 db_vnpy['test'].update_one({"goodsname":'apple1'}, {'$setOnInsert': {"goodsname":'apple1','2':2, '1':1, '3':3}}, upsert=True)

In [9]:
 db_vnpy['test'].drop()

In [12]:
 import pymongo
db_vnpy['test'].create_index([('trade_month', pymongo.ASCENDING), ('ts_code', pymongo.ASCENDING)], unique=True)

'trade_month_1_ts_code_1'

In [1]:
import pandas as pd
import numpy as np

In [9]:
df = pd.DataFrame(np.arange(16).reshape(2,-1), columns=['a','b','c','d','e','f','g','h'])

In [10]:
df

a  b   c   d   e   f   g   h
0  0  1   2   3   4   5   6   7
1  8  9  10  11  12  13  14  15

In [38]:
t1= df['b'] > 2

In [39]:
type(df['b'])

pandas.core.series.Series

In [40]:
t2 = df['c'] > 1

In [41]:
t1

0    False
1     True
Name: b, dtype: bool

In [42]:
t2

0    True
1    True
Name: c, dtype: bool

In [48]:
t1 = np.array(t1, dtype=int)
t1

array([0, 1])

In [49]:
t2 = np.array(t2, dtype=int)
t2

array([1, 1])

In [50]:
t1 + t2

array([1, 2])

In [51]:
df

a  b   c   d   e   f   g   h
0  0  1   2   3   4   5   6   7
1  8  9  10  11  12  13  14  15

In [52]:
df.index

RangeIndex(start=0, stop=2, step=1)

In [53]:
df.index[1]

1

In [65]:
df1 = df.iloc[[False, True]]

In [66]:
df1

a  b   c   d   e   f   g   h
1  8  9  10  11  12  13  14  15

In [72]:
3 in np.array(df.index)

False

In [73]:
cnt = 0
cnt_success = 0
for idx in np.array(df1.index):
    cnt += 1
    if idx in np.array(df.index):
        cnt_success += 1
print(cnt_success/cnt)

1.0


In [74]:
df1.shape[0]

1

In [75]:
df

a  b   c   d   e   f   g   h
0  0  1   2   3   4   5   6   7
1  8  9  10  11  12  13  14  15

In [76]:
df.values

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [81]:
df.values[:, 0:-1]

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [83]:
df.values[:,-1].shape

(2,)

In [1]:
class Dog(object):
    def __init__(self, name):
        self.name = name
    def eat(self):
        print("%s is eatting...", self.name)

In [3]:
d = Dog('digu')
choice = input('>>:').strip() 
print(hasattr(d,choice))

>>:
False
